/**
 * Every design token in `tokens.css`, grouped for the tokens page. A unit
 * test checks this list and the stylesheet agree.
 */
export const TOKEN_GROUPS = {
  palette: [
    '--palette-accent-50',
    '--palette-accent-100',
    '--palette-accent-200',
    '--palette-accent-300',
    '--palette-accent-400',
    '--palette-accent-500',
    '--palette-accent-600',
    '--palette-accent-700',
    '--palette-accent-800',
    '--palette-accent-900',
    '--palette-neutral-0',
    '--palette-neutral-25',
    '--palette-neutral-50',
    '--palette-neutral-100',
    '--palette-neutral-200',
    '--palette-neutral-300',
    '--palette-neutral-400',
    '--palette-neutral-500',
    '--palette-neutral-600',
    '--palette-neutral-700',
    '--palette-neutral-750',
    '--palette-neutral-800',
    '--palette-neutral-850',
    '--palette-neutral-900',
    '--palette-neutral-925',
    '--palette-neutral-950',
    '--palette-red-600',
    '--palette-red-300',
    '--palette-amber-700',
    '--palette-amber-300',
    '--palette-green-700',
    '--palette-green-300',
    '--palette-blue-700',
    '--palette-blue-300',
  ],
  color: [
    '--color-bg',
    '--color-surface-rail',
    '--color-surface-panel',
    '--color-surface-raised',
    '--color-surface-sunken',
    '--color-image-backdrop',
    '--color-overlay',
    '--color-text',
    '--color-text-muted',
    '--color-text-heading',
    '--color-text-disabled',
    '--color-border',
    '--color-border-strong',
    '--color-control-bg',
    '--color-control-border',
    '--color-control-border-hover',
    '--color-control-text',
    '--color-accent',
    '--color-accent-hover',
    '--color-accent-pressed',
    '--color-accent-text',
    '--color-accent-subtle',
    '--color-on-accent',
    '--color-rail-text',
    '--color-rail-hover-bg',
    '--color-rail-active-bg',
    '--color-rail-active-text',
    '--color-focus',
    '--color-danger',
    '--color-warning',
    '--color-success',
    '--color-info',
  ],
  typography: [
    '--font-family-sans',
    '--font-family-display',
    '--font-family-mono',
    '--font-size-xs',
    '--font-size-sm',
    '--font-size-md',
    '--font-size-lg',
    '--font-size-xl',
    '--font-size-2xl',
    '--font-size-3xl',
    '--font-weight-light',
    '--font-weight-regular',
    '--font-weight-medium',
    '--font-weight-semibold',
    '--line-height-tight',
    '--line-height-normal',
  ],
  spacing: [
    '--space-0',
    '--space-1',
    '--space-2',
    '--space-3',
    '--space-4',
    '--space-5',
    '--space-6',
    '--space-8',
    '--space-10',
    '--space-12',
  ],
  radius: ['--radius-sm', '--radius-md', '--radius-lg', '--radius-full'],
  control: [
    '--control-height-sm',
    '--control-height-md',
    '--control-padding-x',
    '--icon-size-xs',
    '--icon-size-sm',
    '--icon-size-md',
    '--border-width',
    '--focus-ring-width',
    '--focus-ring-offset',
  ],
  layout: ['--rail-width', '--rail-item-height', '--pane-width-narrow', '--pane-width-wide'],
  layer: ['--z-rail', '--z-dropdown', '--z-dialog', '--z-toast'],
  elevation: ['--shadow-sm', '--shadow-md', '--shadow-lg'],
  motion: ['--duration-fast', '--duration-normal', '--easing-standard'],
} as const

/** The tokens whose values differ between the light and dark themes. */
export const THEMED_GROUPS = ['color', 'elevation'] as const
